//DUCKS pattren
import { createSlice, PayloadAction } from "@reduxjs/toolkit"

interface counterState {
    value: number
}

const initialState: counterState = {
    value: 0
}

// Reducer logic
const counterSlice = createSlice({
    name: 'counter',
    initialState,
    reducers: {
        incremented: (state) => {
            state.value++
        },
        amountAdd: (state, action: PayloadAction<number>) => {
            state.value += action.payload
        }
    }
})

// Action creator function automaticly generated by createSlice
// Action creator function is function that generated action object
// Action object is plain javascript object that have type and/or payload field
export const { incremented, amountAdd } = counterSlice.actions

// Reducer function(previousState, action) automaticly generated by createSlice
// Reducer function is function that act like event listener that link between action and state
export default counterSlice.reducer